### PR TITLE
update Simplified Chinese Translations

### PR DESCRIPTION
**Pull request by cheriodone**

### CODE REVIEW

**Comment by cheriodone** [comment]
@

**Comment by mbonani** [comment]
Hello @cheriodone, Thank you for you contribution!
Can you control perhaps if the build packet are ok in Chinese ? https://dev.azure.com/mobsya/Thymio%20Software%20Suite/_build/results?buildId=2073&view=artifacts&pathAsName=false&type=publishedArtifacts You can dowload them clicking on the tree dots on the right.

**Comment by cheriodone** [comment]
tried x64 build,it works just fine .laucher discription pages , scratch blocks, vpl3 and blockly still in english. not find files of how to  translate; for the accuracy of translation,will see with my little girl,she's using scratch now.will commit some new if find inaccurate

**Comment by mbonani** [comment]
I have fix scratch translation changing file name in zh-cn, is it correct ? otherwise it is zh-tw
then I have to make a small scratch release to deploy it in the paquet. You can already dowload it here: https://dev.azure.com/mobsya/Thymio%20Software%20Suite/_build/results?buildId=2077&view=artifacts&pathAsName=false&type=publishedArtifacts
 and replace the scratch folder in c:->Programe->Thymio->scratch

**Comment by cheriodone** [comment]
yes ,it's zh-cn.if can finishe all translations will take some time try to do zh-tw,some differeces between cn & tw.

**Comment by mbonani** [comment]
This one as also Scratch in Chinese
https://dev.azure.com/mobsya/Thymio%20Software%20Suite/_build/results?buildId=2081&view=results

**Comment by cheriodone** [comment]
works！but scratch need switch to CN  manually .BTW，can you send me other files need to translate like for vpl3 and blockly etc..

**Comment by mbonani** [comment]
OK for scratch, I do not know why, on my computer it is automatic and normally takes the system language.
For VPL3 I will ask developers.
For Blockly, its is not actively maintain and I am not sure we will continue with it. Translation it is hard to manage yourself, but files are here:  https://github.com/Mobsya/blockly/tree/master/msg/json  you have to add all "THYMIO_*" input from [en.json]( https://github.com/Mobsya/blockly/blob/master/msg/json/en.json) to the [zh-hans.json]( https://github.com/Mobsya/blockly/blob/master/msg/json/zh-hans.json). One time done I can make the builds (not so automatic like the in Thymio Suite.
Last files to translate in Thymio Suite are there: https://github.com/Mobsya/aseba/tree/master/aseba/launcher/src/apps
for each app there is a small description in html format: https://github.com/Mobsya/aseba/blob/master/aseba/launcher/src/apps/blockly/desc.en.html

**Comment by cheriodone** [comment]
blockly finished, and i think for Thymio Suite already been done from my initial pull request.

**Comment by mbonani** [comment]
Thank you for Blockly, I will also get a look to see why tanslatations descriptions are not seens. I let you know when a new packet is availble for testing

**Comment by mbonani** [comment]
Hello, I manage to update your translation of Blockly, but there still one part to translate: https://github.com/Mobsya/thymio-blockly-standalone/blob/master/thymio_blockly/thymio_blockly.zh.html
The file is less obvious but here is want to translate: 

_Cannot find Thymio   !
Connect Thymio to your computer with the   USB cable or the Wireless dongle.
Make sure that Thymio Web Bridge is   active.
About
Authors
Thanks to
Thymio Blockly is an environment for   interactively programming Thymio robots with Blockly language.
More information about Blockly language.
More information about Thymio Blockly.
Thymio Blockly is based on the Aseba   technology, learn more on
Thymio Blockly authors
Based on Aseba by
Other translators
Close
New
Open
Save
Load & Run
Stop
Help
Events
Actuators
LEDs
Sensors
Logic
Loops
Variables
Subroutines
Thymio is not connected_

**Comment by cheriodone** [comment]
image

part of laucher interface still in english, scratch can't switch automatic to chinese.  vpl3 still in english and not find way to change

**Comment by mbonani** [comment]
Hello, thank you for testing. For VPL3 I will send you files by mail. Can you contact me on my email you will found in my profile?
For description I have to look and for scratch I am not sure we can fix, I will have a look.

**Comment by mbonani** [comment]
Hello, latest build contain also Chineese for VPL3, can you please test it. 
Can you also control in the adress bar that the correct language code is there:
image

option to use normal browser is here:
image

**Comment by cheriodone** [comment]
hi,tried  build 20210601.2, language code is case sensitive worked with zh-cn,not zh-CN.
btw,find 3 errors in blockly 
屏幕截图 2021-06-02 074850

屏幕截图 2021-06-02 075331
屏幕截图 2021-06-02 075256
屏幕截图 2021-06-02 075426

**Comment by mbonani** [comment]
Hello, latest paquet is available https://dev.azure.com/mobsya/Thymio%20Software%20Suite/_build/results?buildId=2187&view=artifacts&pathAsName=false&type=publishedArtifacts
Thymio Suite should be in Chinese, also the descriptions
VPL3 automatically in Chinese
Scratch can be put manually in Chinese

I have to work on the bugs you seen Blockly

**Comment by mbonani** [comment]
https://dev.azure.com/mobsya/Thymio%20Software%20Suite/_build/results?buildId=2189&view=artifacts&pathAsName=false&type=publishedArtifacts
should be complete also with BLockly corrections

**Comment by cheriodone** [comment]
tested latest build, all good ,scratch & blockly can be manually switched to Chinese。
the 2nd error in blockly  about timer not changed.

**Comment by mbonani** [comment]
latest build should be complete https://dev.azure.com/mobsya/Thymio%20Software%20Suite/_build/results?buildId=2195&view=artifacts&pathAsName=false&type=publishedArtifacts 
Blockly is also automatically chosen in correct language

**Comment by cheriodone** [comment]
blockly good，scratch can be chosen manually，laucher in Chinese. great work！

**Comment by mbonani** [comment]
Thank you for the translation and testing. I will merge it in master branch.

**Pull request merged**
