### PR TITLE
WirelessConfigurator UI

### PR DESCRIPTION
**Pull request by cor3ntin**

### CODE REVIEW

**Comment by mbonani** [comment]
I made some test, for one problem come from when you pair you send a reboot message but then the USB port is not open quickly. The robot began directly to enumerated in Wireless even if it is connect to USB. This is something that do not happen when you reboot from Studio (so it do not come from Thymio firmware) 
I suggest to stop enumerate trough donglse  when the Wireless configurator is open if possible.

**Comment by mbonani** [comment]
it is working!   just a strange thing is when you have a dongle with a zero as  channel (or 1 in interface) it is not shown (or selected) and pairing crash in this case:

image

**Comment by cor3ntin** [comment]
@mbonani can you retest ?

**Comment by mbonani** [comment]
it works fine, good job

**Pull request merged**
