### PR TITLE
On  windows, do not memorize the device before connecting to it

### LINKED ISSUE #671: regression with Wireless Thymio
when you connect several dongle at same time with a usb hub or quickly on your computer, only one or two correctly connected to the robot, the other ones do not chech for their robots. 
This is a regression in respect of previous version without the Wireless configurator.

### PR DESCRIPTION
**Pull request by cor3ntin**
Fixes #671

### CODE REVIEW

**Comment by mbonani** [comment]
is that change make the improvement on winodws that we can plug 4 wireless at same time, is it possible to do the same on the other os?

**Comment by cor3ntin** [comment]
yes and yes

**Comment by cor3ntin** [comment]
I mean, is there an OS on which it doesn't work?

**Comment by mbonani** [comment]
on OSX 10.12 it do not work if you put all together.  I didn't test on Linux

**Pull request merged**
