### PR TITLE
Deploy msvc

### PR DESCRIPTION
**Pull request by cor3ntin**

### CODE REVIEW

**Comment by mbonani** [comment]
I tested on another computer, ThymioSuite beta (site version)  was working, but neither the nightly or this pull request are working

**Comment by mbonani** [comment]
retested, still not work, is there something to change in the nsis installer?

**Comment by cor3ntin** [comment]
@mbonani can you show me the error message ?

**Comment by mbonani** [comment]
image

**Comment by mbonani** [comment]
error is appear between rc1 and rc2

**Comment by mbonani** [comment]
error appear in commit  af8a5cadd2d78aeac510ad0b7fc6d30553121d64 strange at it is only small graphique changes

**Comment by mbonani** [comment]
working

**Pull request merged**
